# name: Provision or Destroy AWS infrastructure 

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main 

# jobs:
#   provision:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Set up Terraform
#       uses: hashicorp/setup-terraform@v1
#       with:
#         terraform_version: '1.1.0'

#     - name: Configure AWS credentials
#       uses: aws-actions/configure-aws-credentials@v1
#       with:
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws-region: ap-southeast-2
    
#     - name: Terraform provision AWS resources
#       working-directory: ./terraform
#       run: |
#          terraform init
#          terraform apply --auto-approve
  
#   de-provision:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Set up Terraform
#       uses: hashicorp/setup-terraform@v1
#       with:
#         terraform_version: '1.1.0'

#     - name: Configure AWS credentials
#       uses: aws-actions/configure-aws-credentials@v1
#       with:
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws-region: ap-southeast-2
    
#     - name: Terraform provision AWS resources
#       working-directory: ./terraform
#       run: terraform destroy --auto-approve


name: Provision or Destroy Infrastructure
on:
  workflow_dispatch:
    inputs:
      infrastructure:
         description: 'Choose to provision or de-provision'
         required: true
         default: 'provision'
         type: choice
         options:
         - provision
         - deprovision

jobs:
  provision: 
    if: ${{ inputs.infrastructure }} == "provision"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.1.0'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2
    
    - name: Terraform provision AWS resources
      run: |
         terraform init
         terraform apply --auto-approve
  
  de-provision:
    if: ${{ inputs.infrastructure }} == "deprovision"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.1.0'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2
    
    - name: Terraform provision AWS resources
      run: terraform destroy --auto-approve
